-- USER SQL
CREATE USER TEMPLATE_USER IDENTIFIED BY TEMPLATE_USER
  DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP"
      QUOTA UNLIMITED ON users;

      -- SYSTEM PRIVILEGES
      GRANT ALTER TABLESPACE TO TEMPLATE_USER ;
      GRANT ADMINISTER SQL MANAGEMENT OBJECT TO TEMPLATE_USER ;
      GRANT CREATE MINING MODEL TO TEMPLATE_USER ;
      GRANT CREATE TRIGGER TO TEMPLATE_USER ;
      GRANT DEBUG CONNECT SESSION TO TEMPLATE_USER ;
      GRANT CREATE ASSEMBLY TO TEMPLATE_USER ;
      GRANT CREATE SEQUENCE TO TEMPLATE_USER ;
      GRANT ON COMMIT REFRESH TO TEMPLATE_USER ;
      GRANT ADVISOR TO TEMPLATE_USER ;
      GRANT ALTER PROFILE TO TEMPLATE_USER ;
      GRANT CREATE TABLE TO TEMPLATE_USER ;
      GRANT ADMINISTER RESOURCE MANAGER TO TEMPLATE_USER ;
      GRANT BECOME USER TO TEMPLATE_USER ;
      GRANT EXECUTE ASSEMBLY TO TEMPLATE_USER ;
      GRANT CREATE OPERATOR TO TEMPLATE_USER ;
      GRANT ALTER PUBLIC DATABASE LINK TO TEMPLATE_USER ;
      GRANT CREATE EXTERNAL JOB TO TEMPLATE_USER ;
      GRANT CREATE LIBRARY TO TEMPLATE_USER ;
      GRANT CREATE JOB TO TEMPLATE_USER ;
      GRANT CREATE CLUSTER TO TEMPLATE_USER ;
      GRANT CREATE EVALUATION CONTEXT TO TEMPLATE_USER ;
      GRANT CHANGE NOTIFICATION TO TEMPLATE_USER ;
      GRANT ALTER ROLLBACK SEGMENT TO TEMPLATE_USER ;
      GRANT CREATE PROCEDURE TO TEMPLATE_USER ;
      GRANT ADMINISTER SQL TUNING SET TO TEMPLATE_USER ;
      GRANT ALTER DATABASE LINK TO TEMPLATE_USER ;
      GRANT CREATE SYNONYM TO TEMPLATE_USER ;
      GRANT ALTER DATABASE TO TEMPLATE_USER ;
      GRANT CREATE VIEW TO TEMPLATE_USER ;
      GRANT CREATE TYPE TO TEMPLATE_USER ;
      GRANT ALTER RESOURCE COST TO TEMPLATE_USER ;
      GRANT CREATE MEASURE FOLDER TO TEMPLATE_USER ;
      GRANT RESTRICTED SESSION TO TEMPLATE_USER ;
      GRANT ALTER USER TO TEMPLATE_USER ;
      GRANT CREATE SESSION TO TEMPLATE_USER ;
      GRANT QUERY REWRITE TO TEMPLATE_USER ;
      GRANT RESUMABLE TO TEMPLATE_USER ;
      GRANT UNLIMITED TABLESPACE TO TEMPLATE_USER ;
      GRANT CREATE INDEXTYPE TO TEMPLATE_USER ;
      GRANT ALTER SYSTEM TO TEMPLATE_USER ;
      GRANT CREATE MATERIALIZED VIEW TO TEMPLATE_USER ;
      GRANT AUDIT SYSTEM TO TEMPLATE_USER ;
      GRANT CREATE CUBE TO TEMPLATE_USER ;
      GRANT ALTER SESSION TO TEMPLATE_USER ;

